[package]
name = "ringhopper"
authors = ["Snowy Mouse"]
version = "0.2.0"
description = "Library for modding Halo: Combat Evolved"
license = "GPL-3.0-only"

[dependencies]
ringhopper-definitions = { path = "../ringhopper-definitions" }
