[package]
name = "invader"
authors = ["Snowy Mouse"]
version = "0.2.0"
description = "Tool for creating and manipulating content for Halo: Combat Evolved"
license = "GPL-3.0-only"

[dependencies]
ringhopper = { path = "../ringhopper" }
ringhopper-engines = { path = "../ringhopper-engines" }
