[package]
name = "invader"
authors = ["Snowy Mouse"]
version = "0.2.0"
description = "Tool for modding Halo: Combat Evolved"
license = "GPL-3.0-only"

[dependencies]
ringhopper = { path = "../ringhopper" }
