[package]
name = "ringhopper-primitives"
authors = ["Snowy Mouse"]
version = "0.2.0"
description = "Types and utilities for Ringhopper"
license = "GPL-3.0-only"
edition = "2021"

[dependencies]
byteorder = "1.5.0"